"""Add V4 Layer and Account tracking

Revision ID: 66e86b04c216
Revises: 0196def0c66c
Create Date: 2026-04-11 06:59:35.918798

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66e86b04c216"
down_revision: str | None = "0196def0c66c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candidate_scores", sa.Column("layer_id", sa.String(length=10), nullable=True))
    op.add_column("candidate_scores", sa.Column("account_id", sa.String(length=50), nullable=True))
    op.add_column("recommended_trades", sa.Column("layer_id", sa.String(length=10), nullable=True))
    op.add_column(
        "recommended_trades", sa.Column("account_id", sa.String(length=50), nullable=True)
    )
    op.add_column("scan_results", sa.Column("layer_id", sa.String(length=10), nullable=True))
    op.add_column("scan_results", sa.Column("account_id", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("scan_results", "account_id")
    op.drop_column("scan_results", "layer_id")
    op.drop_column("recommended_trades", "account_id")
    op.drop_column("recommended_trades", "layer_id")
    op.drop_column("candidate_scores", "account_id")
    op.drop_column("candidate_scores", "layer_id")
    # ### end Alembic commands ###
