"""initial_schema

Revision ID: cc09f327c5dc
Revises:
Create Date: 2026-04-06 18:00:15.643762

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc09f327c5dc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_app_settings_key"), "app_settings", ["key"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=True),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("provider_source", sa.String(length=50), nullable=True),
        sa.Column("data_freshness", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=True),
        sa.Column("scoring_version", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_event_type"), "audit_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_logs_scan_run_id"), "audit_logs", ["scan_run_id"], unique=False)
    op.create_table(
        "candidate_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("liquidity_score", sa.Float(), nullable=False),
        sa.Column("earnings_timing_score", sa.Float(), nullable=False),
        sa.Column("vol_term_structure_score", sa.Float(), nullable=False),
        sa.Column("containment_score", sa.Float(), nullable=False),
        sa.Column("pricing_efficiency_score", sa.Float(), nullable=False),
        sa.Column("event_cleanliness_score", sa.Float(), nullable=False),
        sa.Column("historical_fit_score", sa.Float(), nullable=False),
        sa.Column("weighted_total", sa.Float(), nullable=False),
        sa.Column("scoring_version", sa.String(length=20), nullable=False),
        sa.Column("score_details_json", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_candidate_scores_scan_run_id"), "candidate_scores", ["scan_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_scores_ticker"), "candidate_scores", ["ticker"], unique=False
    )
    op.create_table(
        "earnings_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("earnings_date", sa.Date(), nullable=False),
        sa.Column("report_timing", sa.String(length=20), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("source_confidence", sa.Float(), nullable=False),
        sa.Column("fiscal_quarter", sa.String(length=10), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_earnings_events_earnings_date"), "earnings_events", ["earnings_date"], unique=False
    )
    op.create_index(op.f("ix_earnings_events_ticker"), "earnings_events", ["ticker"], unique=False)
    op.create_table(
        "option_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("option_type", sa.String(length=4), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("expiration", sa.Date(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("mid", sa.Float(), nullable=True),
        sa.Column("last", sa.Float(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("implied_volatility", sa.Float(), nullable=True),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("gamma", sa.Float(), nullable=True),
        sa.Column("theta", sa.Float(), nullable=True),
        sa.Column("vega", sa.Float(), nullable=True),
        sa.Column("rho", sa.Float(), nullable=True),
        sa.Column("bid_ask_spread", sa.Float(), nullable=True),
        sa.Column("spread_to_mid_ratio", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "snapshot_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_option_snapshots_expiration"), "option_snapshots", ["expiration"], unique=False
    )
    op.create_index(
        op.f("ix_option_snapshots_ticker"), "option_snapshots", ["ticker"], unique=False
    )
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("open", sa.Float(), nullable=False),
        sa.Column("high", sa.Float(), nullable=False),
        sa.Column("low", sa.Float(), nullable=False),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("avg_dollar_volume", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prices_ticker"), "prices", ["ticker"], unique=False)
    op.create_index(op.f("ix_prices_trade_date"), "prices", ["trade_date"], unique=False)
    op.create_table(
        "recommended_trades",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("spot_price", sa.Float(), nullable=False),
        sa.Column("earnings_date", sa.Date(), nullable=False),
        sa.Column("earnings_confidence", sa.String(length=20), nullable=False),
        sa.Column("entry_date_start", sa.Date(), nullable=False),
        sa.Column("entry_date_end", sa.Date(), nullable=False),
        sa.Column("planned_exit_date", sa.Date(), nullable=False),
        sa.Column("short_expiry", sa.Date(), nullable=False),
        sa.Column("long_expiry", sa.Date(), nullable=False),
        sa.Column("lower_strike", sa.Float(), nullable=False),
        sa.Column("upper_strike", sa.Float(), nullable=False),
        sa.Column("total_debit_mid", sa.Float(), nullable=False),
        sa.Column("total_debit_pessimistic", sa.Float(), nullable=True),
        sa.Column("estimated_max_loss", sa.Float(), nullable=False),
        sa.Column("profit_zone_low", sa.Float(), nullable=True),
        sa.Column("profit_zone_high", sa.Float(), nullable=True),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("rationale_summary", sa.Text(), nullable=True),
        sa.Column("key_risks", sa.Text(), nullable=True),
        sa.Column("risk_disclaimer", sa.Text(), nullable=True),
        sa.Column("construction_version", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommended_trades_scan_run_id"),
        "recommended_trades",
        ["scan_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommended_trades_ticker"), "recommended_trades", ["ticker"], unique=False
    )
    op.create_table(
        "rejection_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("stage", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("metric_name", sa.String(length=100), nullable=True),
        sa.Column("metric_value", sa.Float(), nullable=True),
        sa.Column("threshold_value", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_rejection_logs_scan_run_id"), "rejection_logs", ["scan_run_id"], unique=False
    )
    op.create_index(op.f("ix_rejection_logs_ticker"), "rejection_logs", ["ticker"], unique=False)
    op.create_table(
        "scan_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scan_run_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("stage_reached", sa.String(length=50), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("rejection_reasons", sa.Text(), nullable=True),
        sa.Column("rationale_summary", sa.Text(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scan_results_scan_run_id"), "scan_results", ["scan_run_id"], unique=False
    )
    op.create_index(op.f("ix_scan_results_ticker"), "scan_results", ["ticker"], unique=False)
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("universe_hash", sa.String(length=64), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=True),
        sa.Column("scoring_version", sa.String(length=20), nullable=False),
        sa.Column("total_scanned", sa.Integer(), nullable=False),
        sa.Column("total_recommended", sa.Integer(), nullable=False),
        sa.Column("total_watchlist", sa.Integer(), nullable=False),
        sa.Column("total_rejected", sa.Integer(), nullable=False),
        sa.Column("operating_mode", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_runs_run_id"), "scan_runs", ["run_id"], unique=True)
    op.create_table(
        "system_health_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("provider_name", sa.String(length=50), nullable=False),
        sa.Column("is_connected", sa.Boolean(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("last_successful_fetch", sa.DateTime(timezone=True), nullable=True),
        sa.Column("data_freshness_seconds", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "trade_legs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("leg_number", sa.Integer(), nullable=False),
        sa.Column("option_type", sa.String(length=4), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("expiration", sa.Date(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("bid", sa.Float(), nullable=True),
        sa.Column("ask", sa.Float(), nullable=True),
        sa.Column("mid", sa.Float(), nullable=True),
        sa.Column("implied_volatility", sa.Float(), nullable=True),
        sa.Column("delta", sa.Float(), nullable=True),
        sa.Column("theta", sa.Float(), nullable=True),
        sa.Column("vega", sa.Float(), nullable=True),
        sa.Column("open_interest", sa.Integer(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("spread_to_mid", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_legs_trade_id"), "trade_legs", ["trade_id"], unique=False)
    op.create_table(
        "universe_tickers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("market_cap", sa.Float(), nullable=True),
        sa.Column("avg_daily_volume", sa.Float(), nullable=True),
        sa.Column("avg_option_volume", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_universe_tickers_ticker"), "universe_tickers", ["ticker"], unique=True)
    op.create_table(
        "volatility_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("realized_vol_10d", sa.Float(), nullable=True),
        sa.Column("realized_vol_20d", sa.Float(), nullable=True),
        sa.Column("realized_vol_30d", sa.Float(), nullable=True),
        sa.Column("atr_14d", sa.Float(), nullable=True),
        sa.Column("iv_rank", sa.Float(), nullable=True),
        sa.Column("iv_percentile", sa.Float(), nullable=True),
        sa.Column("front_expiry_iv", sa.Float(), nullable=True),
        sa.Column("back_expiry_iv", sa.Float(), nullable=True),
        sa.Column("term_structure_slope", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_volatility_metrics_as_of_date"), "volatility_metrics", ["as_of_date"], unique=False
    )
    op.create_index(
        op.f("ix_volatility_metrics_ticker"), "volatility_metrics", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_volatility_metrics_ticker"), table_name="volatility_metrics")
    op.drop_index(op.f("ix_volatility_metrics_as_of_date"), table_name="volatility_metrics")
    op.drop_table("volatility_metrics")
    op.drop_index(op.f("ix_universe_tickers_ticker"), table_name="universe_tickers")
    op.drop_table("universe_tickers")
    op.drop_index(op.f("ix_trade_legs_trade_id"), table_name="trade_legs")
    op.drop_table("trade_legs")
    op.drop_table("system_health_snapshots")
    op.drop_index(op.f("ix_scan_runs_run_id"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_index(op.f("ix_scan_results_ticker"), table_name="scan_results")
    op.drop_index(op.f("ix_scan_results_scan_run_id"), table_name="scan_results")
    op.drop_table("scan_results")
    op.drop_index(op.f("ix_rejection_logs_ticker"), table_name="rejection_logs")
    op.drop_index(op.f("ix_rejection_logs_scan_run_id"), table_name="rejection_logs")
    op.drop_table("rejection_logs")
    op.drop_index(op.f("ix_recommended_trades_ticker"), table_name="recommended_trades")
    op.drop_index(op.f("ix_recommended_trades_scan_run_id"), table_name="recommended_trades")
    op.drop_table("recommended_trades")
    op.drop_index(op.f("ix_prices_trade_date"), table_name="prices")
    op.drop_index(op.f("ix_prices_ticker"), table_name="prices")
    op.drop_table("prices")
    op.drop_index(op.f("ix_option_snapshots_ticker"), table_name="option_snapshots")
    op.drop_index(op.f("ix_option_snapshots_expiration"), table_name="option_snapshots")
    op.drop_table("option_snapshots")
    op.drop_index(op.f("ix_earnings_events_ticker"), table_name="earnings_events")
    op.drop_index(op.f("ix_earnings_events_earnings_date"), table_name="earnings_events")
    op.drop_table("earnings_events")
    op.drop_index(op.f("ix_candidate_scores_ticker"), table_name="candidate_scores")
    op.drop_index(op.f("ix_candidate_scores_scan_run_id"), table_name="candidate_scores")
    op.drop_table("candidate_scores")
    op.drop_index(op.f("ix_audit_logs_scan_run_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_event_type"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_app_settings_key"), table_name="app_settings")
    op.drop_table("app_settings")
    # ### end Alembic commands ###
