from enum import Enum


class Environment(str, Enum):
    LOCAL = "local"
    DEVELOPMENT = "development"
    STAGING = "staging"
    PRODUCTION = "production"


class RecommendationClass(str, Enum):
    RECOMMEND = "RECOMMEND"
    WATCHLIST = "WATCHLIST"
    NO_TRADE = "NO_TRADE"


class EarningsConfidence(str, Enum):
    CONFIRMED = "CONFIRMED"
    ESTIMATED = "ESTIMATED"
    UNVERIFIED = "UNVERIFIED"


class ReportTiming(str, Enum):
    BEFORE_OPEN = "BEFORE_OPEN"
    AFTER_CLOSE = "AFTER_CLOSE"
    UNKNOWN = "UNKNOWN"


class OptionType(str, Enum):
    CALL = "CALL"
    PUT = "PUT"


class LegSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class HealthSeverity(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    CRITICAL = "CRITICAL"


class OperatingMode(str, Enum):
    STRICT = "STRICT"
    GRACEFUL = "GRACEFUL"


class ScanStage(str, Enum):
    UNIVERSE_ELIGIBILITY = "UNIVERSE_ELIGIBILITY"
    EARNINGS_ELIGIBILITY = "EARNINGS_ELIGIBILITY"
    OPTIONS_CHAIN_QUALITY = "OPTIONS_CHAIN_QUALITY"
    VOLATILITY_SUITABILITY = "VOLATILITY_SUITABILITY"
    PRICE_CONTAINMENT = "PRICE_CONTAINMENT"
    TRADE_CONSTRUCTION = "TRADE_CONSTRUCTION"
    SCORING = "SCORING"
    EXPLAINABILITY = "EXPLAINABILITY"


class RejectionReason(str, Enum):
    NOT_IN_UNIVERSE = "NOT_IN_UNIVERSE"
    INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY"
    NO_CONFIRMED_EARNINGS = "NO_CONFIRMED_EARNINGS"
    EARNINGS_TOO_FAR = "EARNINGS_TOO_FAR"
    EARNINGS_TOO_CLOSE = "EARNINGS_TOO_CLOSE"
    POOR_OPTIONS_LIQUIDITY = "POOR_OPTIONS_LIQUIDITY"
    POOR_TERM_STRUCTURE = "POOR_TERM_STRUCTURE"
    EXCESSIVE_PRE_EARNINGS_MOVEMENT = "EXCESSIVE_PRE_EARNINGS_MOVEMENT"
    EXCESSIVE_DEBIT = "EXCESSIVE_DEBIT"
    POOR_STRIKE_AVAILABILITY = "POOR_STRIKE_AVAILABILITY"
    WIDE_BID_ASK_SPREADS = "WIDE_BID_ASK_SPREADS"
    OVERLAPPING_CATALYSTS = "OVERLAPPING_CATALYSTS"
    STALE_DATA = "STALE_DATA"
    CONSTRUCTION_FAILED = "CONSTRUCTION_FAILED"
    SCORE_BELOW_THRESHOLD = "SCORE_BELOW_THRESHOLD"


class ProviderType(str, Enum):
    EARNINGS = "EARNINGS"
    MARKET_DATA = "MARKET_DATA"
    OPTIONS = "OPTIONS"
    VOLATILITY = "VOLATILITY"
    MACRO_EVENTS = "MACRO_EVENTS"


class UniverseSource(str, Enum):
    STATIC = "STATIC"
    CONFIGURABLE = "CONFIGURABLE"
    SP500_LIQUID = "SP500_LIQUID"
    SP500 = "sp500"
